# Install Prometheus and Grafana
- name: Install Prometheus and Grafana
  hosts: rancher1
  become: yes

  tasks:
    - name: Add Prometheus Helm repository
      command: helm repo add prometheus-community https://prometheus-community.github.io/helm-charts

    - name: Add Grafana Helm repository
      command: helm repo add grafana https://grafana.github.io/helm-charts

    - name: Update Helm repositories
      command: helm repo update

    - name: Install or Upgrade Prometheus
      command: >
        helm upgrade --install prometheus prometheus-community/kube-prometheus-stack \
        --namespace monitoring \
        --create-namespace

    - name: Install or Upgrade Grafana
      command: >
        helm upgrade --install grafana grafana/grafana \
        --namespace monitoring \
        --create-namespace

# Install EFK Stack with helm
- name: Install EFK Stack
  hosts: rancher1
  become: yes

  tasks:
    - name: Add Elastic Helm repository
      command: helm repo add elastic https://helm.elastic.co

    - name: Add Fluent Helm repository
      command: helm repo add fluent https://fluent.github.io/helm-charts

    - name: Update Helm repositories
      command: helm repo update

    - name: Install or Upgrade Elasticsearch
      command: >
        helm upgrade --install elasticsearch elastic/elasticsearch \
        --namespace logging \
        --create-namespace \
        --set elasticsearch.username=elastic \
        --set elasticsearch.password=admin@2024

    - name: Install or Upgrade Fluentd
      command: >
        helm upgrade --install fluentd fluent/fluentd \
        --namespace logging \
        --create-namespace

    - name: Wait for Elasticsearch to be ready
      shell: |
        echo "Waiting for Elasticsearch to be ready..."
        kubectl rollout status statefulset/elasticsearch-master -n logging --timeout=300s

    - name: Install or Upgrade Kibana
      command: >
        helm install kibana elastic/kibana \
        --namespace logging \
        --create-namespace \
        --set elasticsearchHosts=http://elasticsearch-master:9200 \
        --set elasticsearchUsername=elastic \
        --set elasticsearchPassword=admin@2024