---
- name: Install Rancher
  hosts: rancher1
  become: yes

  vars:
    rancher_dns: "{{ hostvars['rancher1']['rancher_dns'] }}"
    letsEncrypt_email: "{{ hostvars['rancher1']['letsEncrypt_email'] }}"

  tasks:
    - name: Install Helm
      shell: curl -L https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | bash

    - name: Apply Rancher Custom CRDs
      command: kubectl apply -f https://github.com/cert-manager/cert-manager/releases/download/v1.11.0/cert-manager.crds.yaml

    - name: Create Cert-Manager Namespace
      command: kubectl create namespace cert-manager

    - name: Create Rancher Namespace
      command: kubectl create namespace cattle-system

    - name: Add Jetstack Helm repository
      command: helm repo add jetstack https://charts.jetstack.io

    - name: Update Helm repositories
      command: helm repo update

    - name: Install Cert-Manager
      command: helm install cert-manager jetstack/cert-manager --namespace cert-manager --version v1.11.0

    - name: Add Rancher Helm repository
      command: helm repo add rancher-stable https://releases.rancher.com/server-charts/stable

    - name: Update Helm repositories
      command: helm repo update

    - name: Install Rancher
      command: >
        helm install rancher rancher-stable/rancher \
          --namespace cattle-system \
          --set hostname={{ rancher_dns }} \
          --set bootstrapPassword=admin \
          --set ingress.tls.source=letsEncrypt \
          --set letsEncrypt.email={{ letsEncrypt_email }} \
          --set letsEncrypt.ingress.class=nginx