---
- name: Install Rancher
  hosts: rancher1
  become: yes

  vars:
    rancher_dns: "{{ hostvars['rancher1']['rancher_dns'] }}"
    letsEncrypt_email: "{{ hostvars['rancher1']['letsEncrypt_email'] }}"

  tasks:
    - name: Install Helm
      shell: curl -L https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | bash

    - name: Apply Rancher Custom CRDs
      command: kubectl apply -f https://github.com/cert-manager/cert-manager/releases/download/v1.11.0/cert-manager.crds.yaml

    - name: Create Cert-Manager Namespace
      command: kubectl create namespace cert-manager
      register: create_cert_manager_namespace
      failed_when: create_cert_manager_namespace.rc != 0 and "AlreadyExists" not in create_cert_manager_namespace.stderr

    - name: Create Rancher Namespace
      command: kubectl create namespace cattle-system
      register: create_rancher_namespace
      failed_when: create_rancher_namespace.rc != 0 and "AlreadyExists" not in create_rancher_namespace.stderr

    - name: Add Jetstack Helm repository
      command: helm repo add jetstack https://charts.jetstack.io

    - name: Update Helm repositories
      command: helm repo update

    - name: Install or Upgrade Cert-Manager
      command: helm upgrade --install cert-manager jetstack/cert-manager --namespace cert-manager --version v1.11.0 --wait

    - name: Add Rancher Helm repository
      command: helm repo add rancher-stable https://releases.rancher.com/server-charts/stable

    - name: Update Helm repositories
      command: helm repo update

    - name: Install or Upgrade Rancher
      command: >
        helm upgrade --install rancher rancher-stable/rancher \
          --namespace cattle-system \
          --set hostname={{ rancher_dns }} \
          --set bootstrapPassword=admin \
          --set ingress.tls.source=letsEncrypt \
          --set letsEncrypt.email={{ letsEncrypt_email }} \
          --set letsEncrypt.ingress.class=nginx
