---
- name: Prepare and install RKE2 agent
  hosts: rancher_agents
  become: yes

  tasks:
    - name: Stop and disable firewall on rancher_agents
      ansible.builtin.systemd:
        name: ufw
        state: stopped
        enabled: no
      when: ansible_os_family == "Debian"
      ignore_errors: yes
      failed_when: false

    - name: Update and install packages on rancher_agents
      apt:
        name:
          - nfs-common
        state: present
        update_cache: yes
      when: ansible_os_family == "Debian"

    - name: Upgrade all packages on rancher_agents
      apt:
        upgrade: dist
        state: latest
      when: ansible_os_family == "Debian"

    - name: Clean up packages on rancher_agents
      apt:
        autoremove: yes
      when: ansible_os_family == "Debian"

    - name: Install RKE2 agent
      shell: curl -sfL https://get.rke2.io | INSTALL_RKE2_TYPE=agent sh -

    - name: Create RKE2 agent config directory
      file:
        path: /etc/rancher/rke2
        state: directory

    - name: Create RKE2 agent config file
      shell: |
        echo "server: https://{{ rancher1_ip }}:9345" > /etc/rancher/rke2/config.yaml
        echo "token: {{ rke2_token }}" >> /etc/rancher/rke2/config.yaml

    - name: Verify RKE2 agent config file
      shell: cat /etc/rancher/rke2/config.yaml
      register: rke2_config
      failed_when: false
      changed_when: false

    - name: Enable RKE2 agent service
      ansible.builtin.systemd:
        name: rke2-agent.service
        enabled: yes

    - name: Start RKE2 agent service
      ansible.builtin.systemd:
        name: rke2-agent.service
        state: started